[project]
name = "agent-core-handson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bedrock-agentcore-starter-toolkit>=0.2.5",
    "boto3>=1.42.19",
]
